---
groups:
- name: onboarding
  jobs:
  - onboarding

jobs:
- name: onboarding
  plan:
  - get: some-git-resource
    trigger: true  
  - get: onboarding-ci
    trigger: true
  - task: onboard
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: latest
      inputs:
      - name: some-git-resource
      run:
        path: sh
        args:
        - -c
        - |
          apt-get update
          apt-get install tree
          cd some-git-resource
          tree .

resources:
- name: some-git-resource
  type: git
  source:
    uri: https://github.com/michelleheh/sandbox-redis-bosh-release
    branch: master
- name: onboarding-ci
  type: git
  source:
    uri: https://github.com/michelleheh/onboarding-concourse
    branch: master