---
groups:
- name: onboarding
  jobs:
  - onboarding

jobs:
- name: onboarding
  plan:
  - get: some-git-resource
    trigger: true  
  - get: onboarding-ci
    trigger: true
  - get: onboarding-docker
    trigger: true
  - task: onboard
    image: onboarding-docker
    config:
      platform: linux
      inputs:
      - name: some-git-resource
      run:
        path: sh
        args:
        - -c
        - tree some-git-resource

resources:
- name: some-git-resource
  type: git
  source:
    uri: https://github.com/michelleheh/sandbox-redis-bosh-release
    branch: master
- name: onboarding-ci
  type: git
  source:
    uri: https://github.com/michelleheh/onboarding-concourse
    branch: master
- name: onboarding-docker
  type: docker-image
  source:
    repository: protondonor/ubuntu-tree